// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofkxkidehimzoblxmvkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ma3hraWRlaGltem9ibHhtdmtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3Njg0NzcsImV4cCI6MjA1NjM0NDQ3N30.K8erEb4ZA8NkWy6gk3YNwP0AnWivxjq8FXHTmaU_W1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);